language: ruby
rvm:
  - 2.4.1

# 分支白名单
branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_47825bfe2df9_key -iv $encrypted_47825bfe2df9_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add ~/.ssh/id_rsa
- git config --global user.name "Travis Bot"
- git config --global user.email rockf91@gmail.com
- cd ~
- git clone git@github.com:rockf91/rockf91.github.io.git build_dir
- cd build_dir
- git checkout -b master

script:
  - bundle install
  - bundle exec jekyll build

after_success:
  - cd build_dir
  - rm -rf * && cp -r ../_site/* .
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push -u origin HEAD:gh-pages --force

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

exclude: [vendor]

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false
cache: bundler
notifications:
  email: false
