language: ruby
rvm:
  - 2.4.1

branches:
  only:
  - master

script:
  - git config --global user.name "Travis Bot"
  - git config --global user.email rockf91@gmail.com
  - cd ~
  - git clone https://github.com/rockf91/rockf91.github.io.git build_dir
  - cd build_dir
  - bundle install
  - bundle exec jekyll build
  - ls
  - mv -f _site ../_site
  - rm -rf *
  - cp -r ../_site/* .
  - ls
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git branch -vv
  - git push --force https://$DEPLOY_TOKEN@github.com/rockf91/rockf91.github.io.git master:gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

exclude: [vendor]

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false
cache: bundler
notifications:
  email: false
